spring.application.name=ms-notification-api

server.port=8081
spring.mvc.converters.preferred-json-mapper=jackson

logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG

spring.profiles.active=local