
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_finance_dev
spring.rabbitmq.password=password_finance_dev

telegram_token=8716116135:AAEVvsdNvBkMNdIgZxrhGrrW3zaPh8xPfvU