spring.application.name=ms-notification-api

server.port=8081
spring.mvc.converters.preferred-json-mapper=jackson

logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_finance_dev
spring.rabbitmq.password=password_finance_dev

telegram_token=8716116135:AAEVvsdNvBkMNdIgZxrhGrrW3zaPh8xPfvU
spring.rabbitmq.addresses=amqps://uyicphvz:jqaYvGgvKA7qm-P_p4EMX9lSvcpSw84r@jaragua.lmq.cloudamqp.com/uyicphvz
