spring.application.name=ms-notification-api

telegram_token=8716116135:AAEVvsdNvBkMNdIgZxrhGrrW3zaPh8xPfvU
server.port=8081

spring.rabbitmq.addresses=amqps://uyicphvz:jqaYvGgvKA7qm-P_p4EMX9lSvcpSw84r@jaragua.lmq.cloudamqp.com/uyicphvz

# Configuração extra recomendada para Jackson conseguir serializar Records/DTOs como JSON na fila
spring.mvc.converters.preferred-json-mapper=jackson