spring.application.name=ms-notification-api

server.port=8081
spring.mvc.converters.preferred-json-mapper=jackson

logging.level.org.springframework.amqp=DEBUG
logging.level.com.rabbitmq=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_finance_dev
spring.rabbitmq.password=password_finance_dev

telegram_token=${TELEGRAM_TOKEN:}
spring.rabbitmq.addresses=${RABBIT_ADDRESS:}