version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: ms-finance-db
    environment:
      POSTGRES_USER: user_finance_dev
      POSTGRES_PASSWORD: password_finance_dev
      POSTGRES_DB: db_finance_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge