server:
  port: 8092

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-notification
              uri: http://localhost:8081
              predicates:
                - Path=/notification/**
              filters:
                - StripPrefix=1

            - id: ms-finance
              uri: http://localhost:8080
              predicates:
                - Path=/finance/**
              filters:
                - StripPrefix=1