spring.application.name=ms-finance-api
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
notion.api.url=https://api.notion.com/v1
gemini.api.url=https://generativelanguage.googleapis.com
