spring.application.name=ms-finance-api

spring.datasource.url=jdbc:postgresql://localhost:5432/db_finance_dev
spring.datasource.username=user_finance_dev
spring.datasource.password=password_finance_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_finance_dev
spring.rabbitmq.password=password_finance_dev

notion.api.url=https://api.notion.com/v1
notion.token=${NOTION_API_TOKEN:}
notion.database.id=${NOTION_DATABASE_ID:}

gemini.token=${GEMINI_API_TOKEN:}
gemini.api.url=https://generativelanguage.googleapis.com
spring.rabbitmq.addresses=${RABBIT_ADDRESS:}
