
spring.datasource.url=jdbc:postgresql://localhost:5432/db_finance_dev
spring.datasource.username=user_finance_dev
spring.datasource.password=${DB_PASSWORD:}

notion.token=${NOTION_API_TOKEN:}
notion.database.id=${NOTION_DATABASE_ID:}

gemini.token=${GEMINI_API_TOKEN:}
spring.rabbitmq.addresses=${CLOUDAMQP_URL:}