spring.application.name=ms-finance-api

# Configuração do Banco de Dados Local (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_finance
spring.datasource.username=user_finance_dev
spring.datasource.password=password_finance_dev
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Credenciais do CloudAMQP (Para o Finance ler a fila da nuvem de forma local)
spring.rabbitmq.addresses=amqps://uyicphvz:jqaYvGgvKA7qm-P_p4EMX9lSvcpSw84r@jaragua.lmq.cloudamqp.com/uyicphvz
