spring.application.name=ms-finance-api

spring.datasource.url=jdbc:postgresql://localhost:5432/db_finance_dev
spring.datasource.username=user_finance_dev
spring.datasource.password=password_finance_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user_finance_dev
spring.rabbitmq.password=password_finance_dev

notion.api.url=https://api.notion.com/v1
notion.token=${notion_api_token}
notion.database.id=39671a34fe7f80f4b6aec578626b4ee1